rootProject.name = "vcord"

include(":core:model")
include(":core:manager")
include(":ui:model")
include(":ui:controller")
include(":ui:impl")
include(":integration:audio")
include(":integration:discord")
include(":integration:discord:mock")
include(":integration:discord:real")
include(":integration:midi")
include(":launcher")
include(":launcher:mock")
include(":launcher:real")
